from .deployment_types import DeploymentTypeSerializer
from .deployment_types import DeploymentTypeDetailSerializer

from .sampling_event_types import SamplingEventTypeSerializer
from .sampling_event_types import SamplingEventTypeDetailSerializer
