from .locality_types import LocalityTypeViewSet
from .localities import LocalityViewSet
from .site_descriptor_types import SiteDescriptorTypeViewSet
from .site_descriptors import SiteDescriptorViewSet
