from .annotation_types import AnnotationTypeSerializer
from .annotation_types import AnnotationTypeDetailSerializer

from .event_types import EventTypeSerializer
from .event_types import EventTypeDetailSerializer
